### ISSUE TITLE
[v.1.0.3] Implicit dependency on Magmodules_GoogleShopping extension

### ISSUE THREAD

**Issue by vpodorozh** [magmodules/magento2-sooqr#11]
There is an implicit dependency on Magmodules_GoogleShopping extension.
However, there are no mentions of Magmodules_GoogleShopping extension in composer.json and module.xml files.

References:
```
app/code/Magmodules/Sooqr/etc/adminhtml/system.xml:247 (require Magmodules\GoogleShopping\Block\Adminhtml\Magmodules\Heading)
app/code/Magmodules/Sooqr/Block/Adminhtml/System/Config/Form/Field/Filters.php:60 (require Magmodules\Sooqr\Block\Adminhtml\System\Config\Form\Field\Renderer\Attributes)
app/code/Magmodules/Sooqr/Block/Adminhtml/System/Config/Form/Field/Filters.php:78 (require \Magmodules\GoogleShopping\Block\Adminhtml\System\Config\Form\Field\Renderer\Conditions)
```

Also, current extension contains similar classes (and they can be used instead), that are required from Magmodules_GoogleShopping.
Please check if this dependency is needed, if yes then add it to package definition.

**Comment by Marvin-Magmodules** [comment]
Fixed in 1.0.4: https://github.com/magmodules/magento2-sooqr/releases/tag/1.0.4
