### ISSUE TITLE
[v.1.0.6] Reflection Exception in Magmodules_Sooqr extension 

### ISSUE THREAD

**Issue by ygyryn** [magmodules/magento2-sooqr#15]
There is an Reflection exception in Magento Back-office when try to open:
Stores->Configuration->Magmodules->Sooqr Connect
*Exception #0 (ReflectionException): Class Magmodules\Sooqr\Model\System\Config\Source\Tax does not exist.*

It is declared in file: app/code/Magmodules/Sooqr/etc/adminhtml/system.xml in 
<source_model>Magmodules\Sooqr\Model\System\Config\Source\Tax</source_model>
Please fix it.

**Comment by Marvin-Magmodules** [comment]
Fixed and repacked 1.0.6: https://github.com/magmodules/magento2-sooqr/releases/tag/1.0.6
Missing file: https://github.com/magmodules/magento2-sooqr/commit/c072b619f775ef16455bf219f7e740afc90a9ae1
