### ISSUE TITLE
Custom JS field creates HTML entities

### ISSUE THREAD

**Issue by Stevie-Ray** [magmodules/magento2-sooqr#29]
When using v1.1.1 of the Sooqr module and applying custom JavaScript in:

**Magmodules / Sooqr Connect / Frontend Implementation / Custom JS**

` _wssq.push(['suggest._setPosition', 'screen-middle'], {top:85});`

results in: 

` _wssq.push([&#39;suggest._setPosition&#39;, &#39;screen-middle&#39;], {top:85});`

**Comment by Marvin-Magmodules** [comment]
Hi @Stevie-Ray thank you for the issue report. Just releases [1.1.2](https://github.com/magmodules/magento2-sooqr/releases/tag/1.1.2) release that fixes this issue.  We are closing this issue now but please feel free to reopen the issue if this still occurs.
