### ISSUE TITLE
Error with Magento 2.4.0 and php 7.4.9

### ISSUE THREAD

**Issue by visualwebs** [magmodules/magento2-sooqr#35]
Hi guys.

Just want to report this error running 2.4.0 and php 7.4.9 under Apache web server.

 Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in magento_install_root/vendor/magmodules/magento2-sooqr/Helper/Feed.php on line 250.

It´s just set that line as this one 

`$current = ord($value[$i]);`

Case you want to fix asap.

Thanks.

**Comment by Frank-Magmodules** [comment]
Hi @visualwebs ,
We are happy to share that we've just released the new [1.1.6](https://github.com/magmodules/magento2-sooqr/releases/tag/1.1.6) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
