### ISSUE TITLE
Widget not filtered from CMS content

### ISSUE THREAD

**Issue by rikwillems** [magmodules/magento2-sooqr#38]
The feed for CMS pages has the {{widget ...}} codes in it. These should be filtered out as they now are being displayed in the text at search result.

**Comment by Frank-Magmodules** [comment]
HI @rikwillems ,

We are happy to share that we've just released version [1.1.8](https://github.com/magmodules/magento2-sooqr/releases/tag/1.1.8) with a fix for this issue. Thank you for opening this request and for your patience. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
