### ISSUE TITLE
Wrong image-link for grouped item of configurable magento product in sooqr xml

### ISSUE THREAD

**Issue by geertbuyse** [magmodules/magento2-sooqr#42]
**Describe the bug**
Sooqr connect module makes it possible to group all individual products of a configurable product based on the assoc-id in the resulting xml file.
However when this xml data feed is uploaded in sooqr the grouped item is always shown with the image-link of the first underlying individual products and this is not correct.
Better would be to detect the image-link of the related assoc-id and use this as the image-link for every underlying individual products.

Example of actual xml of individual product of a configurable product (with assoc-id 27829) :

<item>
   <sqr:content_type>product</sqr:content_type>
   <sqr:id>27654</sqr:id>
   <sqr:title>Truckerspet Chiro</sqr:title>
   <sqr:sku>8530001</sqr:sku>
   <sqr:link>https://www.debanier.be/truckerspet-chiro.html</sqr:link>
   <sqr:description>Leuke Chiropet, verkrijgbaar in de afdelingskleuren. Houdt het hoofd koel op zonnige dagen.</sqr:description>
   <sqr:image_link>https://www.debanier.be/media/catalog/product/8/5/8530001-8530001-afbeelding_1-8530001.jpg</sqr:image_link>
   <sqr:normal_price>7.50</sqr:normal_price>
   <sqr:normal_price_ex>6.20</sqr:normal_price_ex>
   <sqr:price>7.500000</sqr:price>
   <sqr:price_ex>6.20</sqr:price_ex>
   <sqr:currency>EUR</sqr:currency>
    <sqr:product_object_type>simple</sqr:product_object_type>
    <sqr:assoc_id>27829</sqr:assoc_id>
   <sqr:is_bundle>false</sqr:is_bundle>
   <sqr:is_parent>false</sqr:is_parent>
  </item>

This image-link of the first product is always shown and this should be the image-link of the configurable product with assoc_id 27829

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.6
- *Open source/Enterprise/B2b*: Open Source
- *Sooqr version number (Check configuration)*: 1.2.0

**Screenshots**

**Additional context**

**Comment by geertbuyse** [comment]
This is the xml example :

`<item>
   <sqr:content_type>product</sqr:content_type>
   <sqr:id>27654</sqr:id>
   <sqr:title>Truckerspet Chiro</sqr:title>
   <sqr:sku>8530001</sqr:sku>
   <sqr:link>https://www.debanier.be/truckerspet-chiro.html</sqr:link>
   <sqr:description>Leuke Chiropet, verkrijgbaar in de afdelingskleuren. Houdt het hoofd koel op zonnige dagen.</sqr:description>
   <sqr:image_link>https://www.debanier.be/media/catalog/product/8/5/8530001-8530001-afbeelding_1-8530001.jpg</sqr:image_link>
   <sqr:normal_price>7.50</sqr:normal_price>
   <sqr:normal_price_ex>6.20</sqr:normal_price_ex>
   <sqr:price>7.500000</sqr:price>
   <sqr:price_ex>6.20</sqr:price_ex>
   <sqr:currency>EUR</sqr:currency>
   <sqr:product_object_type>simple</sqr:product_object_type>
   <sqr:assoc_id>27829</sqr:assoc_id>
   <sqr:is_bundle>false</sqr:is_bundle>
   <sqr:is_parent>false</sqr:is_parent>
  </item>`

**Comment by Marvin-Magmodules** [comment]
HI @geertbuyse

We are happy to share that we've just released version [1.4.0](https://github.com/magmodules/magento2-sooqr/releases/tag/1.4.0) with a fix for this issue. Thank you for opening this request and for your patience. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
