### ISSUE TITLE
Version number in configuration not being updated

### ISSUE THREAD

**Issue by Aquive** [magmodules/magento2-sooqr#49]
**Describe the bug**
I just updated the Sooqr module to the latest version (v1.5.0) on my local machine. But in the configuration it still lists the old version number (v1.1.9).

**Used versions**
- Magento Open Source 2.4.3-p2 
- Sooqr version number: 1.5.0

**To Reproduce**
Install new version `composer require magmodules/magento2-sooqr:1.5.0`

**Expected behavior**
New version being reflected in the config.

**Actual behavior**
Older version being shown in the config.

**Additional context**
This is also the case when running a deploy to our test server. Tested in dev and production modes.

**Comment by Marvin-Magmodules** [comment]
Hi Aquive, thank you for opening this issue! I'm not able to reproduce this issue, after updated the module to the latest version the admin shows the correct version nummer. This version number is pulled from: https://github.com/magmodules/magento2-sooqr/blob/master/etc/config.xml#L14

Can you double check if this has the correct version number? 
I'm 99% sure you already did, but can you also try and do a full cache flush (magento/redis) to see if this changes anything?

**Comment by Aquive** [comment]
@Marvin-Magmodules 

Thank you for your reply.

- I rechecked etc/config.xml, it has version `v1.5.0`
- I flushed Redis cache
- I flushed Magento cache
- I rechecked for overriding entries in config.php, env.php and in core_config_data table. None of those had an entry for version
- I rechecked version number in the Magento admin backend. It still lists `v1.1.9`

The thing is, I think the extension is actually updated since I see new options became available. 

```
Add to cart Controller
Use Ajax based Add to Cart 

```

Those are new options, right?

Did you test your upgrade from v1.1.9 to v1.5.0?

**Comment by Marvin-Magmodules** [comment]
@Aquive, also tested this using a clean installation from v1.1.9 and update to v1.5.0 but still unable to reproduce this issue. Do you have a dev env available with this issue where we can debug this? If possible, please contact us directly through our <a href="https://www.magmodules.eu/support-form.html">contact form</a> so we can exchange some logins.

**Comment by Aquive** [comment]
It seems it is coming from app/etc/config.php (after a config:dump). I had checked it since I assumed it was the source. But I guess I overlooked it. Solved. Thanks for the support.
