### ISSUE TITLE
Magento 2.4.5 compatible?

### ISSUE THREAD

**Issue by Aquive** [magmodules/magento2-sooqr#52]
**Describe the bug**
Console error in checkout:

`Uncaught ReferenceError: _wssq is not defined
    at add-to-cart.js:8:9`

**Used versions**
- *Magento Open Source*:  2.4.5-p1
- *Sooqr version number (Check configuration)*: 1.6.0

**To Reproduce**
1. Add product to cart
2. Go to checkout
3. Check browser console

**Expected behavior**
No errors

**Actual behavior**
Error visible

**Comment by Marvin-Magmodules** [comment]
Hi @Aquive, we are not able to reproduce this issue,  can you share us the frontend url using: https://www.magmodules.eu/contact-us.html

**Comment by Aquive** [comment]
@Marvin-Magmodules thank you for your reply. It might have been a local issue, since I cannot reproduce it either on our test server. Closing this.
