### ISSUE TITLE
Hypernode issue (/data/web)

### ISSUE THREAD

**Issue by ruthgeridema** [magmodules/magento2-sooqr#57]
**Describe the bug**

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6.-p3
- *Open source/Enterprise/B2b*: open source
- *Sooqr version number*: 2.0.1
**To Reproduce**
On a hypernode, execute sooqr:gen:feed
**Expected behavior**
Feed copy should work

**Actual behavior**
The file or directory "/data/web/magento2/pub/media/sooqr/data/sooqr-1-1706617649.xml" cannot be copied to "/web/magento2/pub/media/sooqr/sooqr-1.xml" Warning!copy(/web/magento2/pub/media/sooqr/sooqr-1.xml): Failed to open stream: No such file or directory

The file or directory "/data/web/magento2/pub/media/sooqr/data/sooqr-2-1706617650.xml" cannot be copied to "/web/magento2/pub/media/sooqr/sooqr-2.xml" Warning!copy(/web/magento2/pub/media/sooqr/sooqr-2.xml): Failed to open stream: No such file or directory

**Additional context**

    if ($type == FeedType::FULL) {
                $this->file->copy($filePath, str_replace('/data/', '/', $this->getFilePath($type, $storeId)));
            }

**Comment by Marvin-Magmodules** [comment]
@ruthgeridema thank you for opening this issue. The referred code indeed looks weird, will look into this issue asap and come back with a fix.

**Comment by Marvin-Magmodules** [comment]
Hi @ruthgeridema just released [v2.0.2](https://github.com/magmodules/magento2-sooqr/releases/tag/2.0.2) that holds a fix for this issue. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
