### ISSUE TITLE
Prices incl Tax bug

### ISSUE THREAD

**Issue by visualwebs** [magmodules/magento2-sooqr#58]
**Describe the bug**
We have a Magento store with those settings:
Admin prices exclude tax
Display prices tax incl in the frontend.
So guest customers see 21% Tax in the prices in the frontend

The problem is Sooqr uses the excl tax prices in the feed, in tags like "price", "final_price" and so on, so the search engine shows the preview of products missing the TAX.

**Used versions**
- *Magento Version number 2.4.6-p1 Open source
- *Sooqr module version number 2.0.0

**Comment by Marvin-Magmodules** [comment]
Hi @visualwebs, thank you for opening this issue! Just released [v2.0.2](https://github.com/magmodules/magento2-sooqr/releases/tag/2.0.2) that holds a fix for this issue. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
