### ISSUE TITLE
Return type in interface breaks SOAP API

### ISSUE THREAD

**Issue by ainigma32** [magmodules/magento2-sooqr#60]
On this line: https://github.com/magmodules/magento2-sooqr/blob/cf7c639f1ec7a2040f28bb4f1cbad1b531330b9c/Api/WebApi/RepositoryInterface.php#L18 the return type is defined as "array" This will result in an error when using the SOAP API: The "array" class doesn't exist and the namespace must be specified. Verify and try again.

The return type shou;d be defined as `string[]`

**Used versions**
- Magento Version: 2.4.6-p3
- Open source
- Sooqr version number 2.0.2

**To Reproduce**
1. Install version 2.0.2
2. Request an aribitrary WSDL URL
3. See error

**Expected behavior**
Show WSDL content

**Actual behavior**
Error occurs: The "array" class doesn't exist and the namespace must be specified. Verify and try again.

**Comment by Marvin-Magmodules** [comment]
Hi @ainigma32, thank you for opening this issue with detailed error report!  Just released [v2.0.3](https://github.com/magmodules/magento2-sooqr/releases/tag/2.0.3) that holds a fix for this issue. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
