### ISSUE TITLE
Inheriting values from parent not working

### ISSUE THREAD

**Issue by rexterkate-adwise** [magmodules/magento2-sooqr#68]
**Describe the bug**
Inheriting values from parent (configurable) product not working for simple products

**Used versions**
- *Magento 2.4.6-p4*
- *Open source*
- *Sooqr version 2.0.7*

**To Reproduce**
1. Configure visible ('Catalog, Search') configurable product and 'Not Visible Individually' simple products
2. Goto 'Stores' -> 'Configuration' -> 'Sooqr' -> 'Data'
3. Set setting 'Use Configurable/Simple Products' to 'Only Linked Simple Products'
4. Set setting 'Use Parent URL for Simples' to 'Yes' (or 'Yes with Auto-Link')
5. Generate Sooqr feed

**Expected behavior**
The simple products in the feeds shoud contain a link to the parent configurable products

**Actual behavior**
The sqr:link tag is empty

**Screenshots**
na

**Additional context**
We have (temporarily) worked around / fixed this problem with patch below
[magmodules-sooqr-parent-fix.patch](https://github.com/magmodules/magento2-sooqr/files/15164394/magmodules-sooqr-parent-fix.patch)

**Comment by Frank-Magmodules** [comment]
Hello @rexterkate-adwise,

I appreciate you bringing this issue to our attention! I see you've raised it using Sooqr version 2.0.7. We've recently rolled out [version 2.1.0](https://github.com/magmodules/magento2-sooqr/releases), which includes enhancements for the `sqr:link` tag, particularly for configurable/grouped and bundled products, similar to what you've described. Could you please confirm if you encounter the same issue with our latest release?

Thanks!

**Comment by Frank-Magmodules** [comment]
Hey @rexterkate-adwise, just wanted to check if you've seen my message above. :) Thanks a bunch!

**Comment by Frank-Magmodules** [comment]
Hi There @rexterkate-adwise ,

I hope you're well. We just rolled out a [new version](https://github.com/magmodules/magento2-sooqr/releases) featuring enhancements to the parent/simple relations. 
Could you kindly confirm if this also addresses the issue you reported?

**Comment by rexterkate-adwise** [comment]
Looking at the code changes it seems to be resolved. Thanks!
