### ISSUE TITLE
Categories in feeds aren't filtered based on the root category

### ISSUE THREAD

**Issue by rexterkate-adwise** [magmodules/magento2-sooqr#70]
**Describe the bug**
Only categories that are children of the root-category should be included in the feed. Now all categories are included

**Used versions**
- *Magento 2.4.6-p5*:
- *Open source*:
- *Sooqr 2.1.1*:

**To Reproduce**
1. On a multistore Magento environment
2. Set the 'Root Category' (Stores -> All Stores -> Pick the Store to edit) to different categories for each store
3. Generate or preview Sooqrfeeds
4. All categories (inside and outside the root category) are shown in the feeds for each store

**Expected behavior**
Only categories that are children of the root-category are included in the feed voor each store

**Actual behavior**
All categories (inside and outside the root category) are shown in the feeds for each store

**Screenshots**
n.a.

**Additional context**
Temporarily patch we use to work around the problem (only tested for our usecase)

[magmodules-sooqr-fix-root-category.patch](https://github.com/magmodules/magento2-sooqr/files/15417716/magmodules-sooqr-fix-root-category.patch)

**Comment by Marvin-Magmodules** [comment]
Hi @rexterkate-adwise, thank you for opening this issue and also supplying the patch! Just released [v2.1.2](https://github.com/magmodules/magento2-sooqr/releases/tag/2.1.2) that includes this patch. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
