### ISSUE TITLE
Product enabled status only checked for default storeview

### ISSUE THREAD

**Issue by npluimers** [magmodules/magento2-sooqr#71]
**Describe the bug**
Products that are enabled on default, and disabled on a specific storeview are being included in the product feed, causing missing products.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p6
- *Open source/Enterprise/B2b*: Open Source
- *Sooqr version number (Check configuration)*: 2.1.1

**To Reproduce**
1. Add Product A, enabled on default, and disable on one storeview
2. Generate feeds
3. Check feed of storeview where product A is disabled

**Expected behavior**
Product A is not included in the feed since the product is not enabled on the specific storeview

**Actual behavior**
Product A is included in the feed

**Additional context**
We have created a patch: https://gist.github.com/npluimers/f8d6475369514d34629af8d620ce3353

**Comment by Marvin-Magmodules** [comment]
Hi @npluimers, thank you for opening this issue and also supplying the patch! Just released [v2.1.2](https://github.com/magmodules/magento2-sooqr/releases/tag/2.1.2) that includes this patch. We added some extra code to this patch to also check for visibility fallback on default store, as while testing we found out that part was still not working properly. 

We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
