### ISSUE TITLE
Price being taken from default storeview instead of specific storeview

### ISSUE THREAD

**Issue by npluimers** [magmodules/magento2-sooqr#72]
**Describe the bug**
Products that have a price on default, and another price on a specific storeview are displaying the price of the default value instead of the specific storeview 

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p6
- *Open source/Enterprise/B2b*: Open Source
- *Sooqr version number (Check configuration)*: 2.1.1

**To Reproduce**
1. Add Product A, price: 100 on default storeview, and price 200 on another storeview
2. Generate feeds
3. Check feed of storeview where product A is set to 200

**Expected behavior**
Price is set to 200 for product A

**Actual behavior**
Price is set at 100 for product A

**Additional context**
We have created a patch: https://gist.github.com/npluimers/869504a82021effba1f6224a8716ef45

**Comment by Marvin-Magmodules** [comment]
Hi @npluimers, thank you for opening this issue and also supplying the patch! Just released [v2.1.2](https://github.com/magmodules/magento2-sooqr/releases/tag/2.1.2) that includes this patch. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
