### ISSUE TITLE
Multi Source Inventory isn't taken in consideration

### ISSUE THREAD

**Issue by rexterkate-adwise** [magmodules/magento2-sooqr#74]
**Describe the bug**
Stock definedin Multi Source Inventory isn't taken in consideration for the stock status

**Used versions**
- *Magento v2.4.6-p5*:
- *Open source*:
- *Sooqr v2.1.1*:

**To Reproduce**
1. Set product stock for default source to be out-of-stock
2. Configure extra Magento MSI sources
3. Assign extra MSI stock sources to product with a positive stock (in-stock)

**Expected behavior**
The product shows the product to be in-stock

**Actual behavior**
The product shows the product to be out-of-stock

**Screenshots**
n/a

**Additional context**
When productData is collected, the array contains a key 'msi' with the non default stock. It doesn't seem to be taken in consideration when creating the actual feed.

**Comment by Marvin-Magmodules** [comment]
@rexterkate-adwise thank you for opening this issue. Sorry for the late reply, but we are having a hard time reproducing this. We use the `inventory_stock_x` tables as these contains aggregated stock quantities and stock status. Can you double check the data in this table/view to see if this is up to date? The product is also In-stock on the frontend for this linked store-view?

**Comment by rexterkate-adwise** [comment]
@Marvin-Magmodules we have reverted all our (multistore) shops to the 1.6.1 version of the plugin because of the problems since the 2.0.0 version. So I can't easily reproduce this currently.

From what ik recall, the msi stock data is correctly read from the database and available in the productData array ('msi' key), but it isn't used in the feed (only 'qty' key is used).

**Comment by Frank-Magmodules** [comment]
Hi there @rexterkate-adwise, apologies for the delay on this. We have just created a [branch](https://github.com/magmodules/magento2-sooqr/compare/fix/msi-support) that should be compatible with the MSI environment where you’ve been experiencing these issues. Could you please test this in a staging/development environment and let me know if it meets your expectations and resolves the issue?

Thanks a lot!

**Comment by Frank-Magmodules** [comment]
Hi @rexterkate-adwise, 
Did you have a chance to look into this? It would be great if we could finalize, merge, or close this issue. Thanks!

**Comment by Marvin-Magmodules** [comment]
Hi @rexterkate-adwise, happy to tell you we merged this into the [v2.2.0](https://github.com/magmodules/magento2-sooqr/releases/tag/2.2.0) relaase so we will consider the issue closed. However, if you encounter any further problems related to this, please don't hesitate to inform us by re-opening this issue.
